#!/bin/sh

intern=LVDS-1
extern=HDMI-1

if xrandr | grep "$extern connected"
then
    main=$extern
    hsetroot -root -cover ~/.config/wallpapers/Reflections_of_the_night_sky.png
else
    main=$intern
    hsetroot -cover ~/.config/wallpapers/Reflections_of_the_night_sky_16_9.png
fi
xrandr --output $main --primary

setxkbmap it
brightnessctl -q set 25%
xrdb ~/.Xresources
# xsetroot -cursor_name left_ptr

exec bspwm
