#!/bin/sh

intern=LVDS-1
extern=HDMI-1

if xrandr | grep "$extern connected" | grep "3440x1440"
then
    xrandr --output $intern --off
    hsetroot -root -cover ~/.config/wallpapers/Reflections_of_the_night_sky.png
    xrandr --output $extern --primary
else
    if xrandr | grep "$extern connected" | grep "1024x768"
    then
        hsetroot -root -cover ~/.config/wallpapers/Reflections_of_the_night_sky.png
        xrandr --output $intern --primary
        xrandr --output $extern --left-of $intern
    else
        hsetroot -cover ~/.config/wallpapers/Reflections_of_the_night_sky_16_9.png
        xrandr --output $intern --primary
    fi
fi

setxkbmap it
brightnessctl -q set 25%
xrdb ~/.Xresources
# xsetroot -cursor_name left_ptr

exec bspwm
