mxid: '@foxy:teapot.ovh'
device_id: DIMYOUTFIT
access_token: syt_Zm94eQ_PSnIyXMSexzOitXfqEKg_07uK3J
homeserver: matrix.teapot.ovh
room_cache_size: 32
room_cache_age: 60
notify_sound: true
send_to_verified_only: false
backspace1_removes_word: true
backspace2_removes_word: false
always_clear_screen: true
data_dir: /home/foxy/.local/share/gomuks
cache_dir: /home/foxy/.cache/gomuks
history_path: /home/foxy/.cache/gomuks/history.db
room_list_path: /home/foxy/.cache/gomuks/rooms.gob.gz
media_dir: /home/foxy/.cache/gomuks/media
download_dir: /home/foxy/downloads/chats
state_dir: /home/foxy/.cache/gomuks/state
