#!/bin/sh

/usr/libexec/xfce-polkit &
picom &
pgrep -x sxhkd > /dev/null || sxhkd &
pulseaudio --start

intern=LVDS-1
extern=HDMI-1
if xrandr | grep "$extern connected" | grep "3440x1440"
then
    bspc monitor $extern -d I II III IV V VI VII VIII IX X
    output=$extern polybar informative &
else
    if xrandr | grep "$extern connected" | grep "1024x768"
    then
        bspc monitor $intern -d I II III IV V
        bspc monitor $extern -d VI VII VIII IX X --left-of $intern
        output=$intern polybar informative &
        output2=$extern polybar minimal &
    else
        bspc monitor $intern -d I II III IV V VI VII VIII IX X
        output=$intern polybar informative &
    fi
fi

bspc config border_width              0
bspc config window_gap                15
bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config top_monocle_padding       -29
bspc config bottom_monocle_padding    -29
bspc config presel_feedback_color     "#011627"
