#!/bin/sh

/usr/libexec/xfce-polkit &

picom &
polybar top-bar &
polybar bottom-bar &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor LVDS-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X
bspc monitor VGA-1 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  -29
bspc config bottom_monocle_padding -29
bspc config ignore_ewmh_focus	 true