#!/bin/sh

/usr/libexec/xfce-polkit &
picom &
pgrep -x sxhkd > /dev/null || sxhkd &

intern=LVDS-1
extern=HDMI-1
output=$intern polybar informative &
if xrandr | grep "$extern connected"
then
    bspc monitor $intern -d 1 2 3 4 5
    bspc monitor $extern -d 6 7 8 9 10
    output=$extern polybar minimal &
else
    bspc monitor $intern -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width              0
bspc config window_gap                5
bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config top_monocle_padding       -29
bspc config bottom_monocle_padding    -29
