#!/bin/sh

/usr/libexec/xfce-polkit &
polybar example &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor LVDS-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X
bspc monitor VGA-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  -29
bspc config bottom_monocle_padding -29
bspc config normal_border_color   '#000028'
bspc config focused_border_color  '#00003C'
bspc config urgent_border_color   '#000050'