#!/bin/sh

/usr/libexec/xfce-polkit &
picom &
pgrep -x sxhkd > /dev/null || sxhkd &
pulseaudio --start

intern=LVDS-1
extern=HDMI-1
if xrandr | grep "$extern connected"
then
    main=$extern
else
    main=$intern
fi
bspc monitor $main -d I II III IV V VI VII VIII IX X
output=$main polybar informative &

bspc config border_width              0
bspc config window_gap                15
bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config top_monocle_padding       -29
bspc config bottom_monocle_padding    -29
bspc config presel_feedback_color     "#011627"
