background="#000000"
text="#ffffff"
subtle="#c2c2c2"
warning-text="#ffbf80"
text-special-one="#ff99cc"
text-special-two="#d78787"
top-bar-background="#9f0000"
top-bar-text="#ffffff"
status-bar-background="#9f0000"
status-bar-text="#ffffff"
status-bar-view-background="#af0000"
status-bar-view-text="#ffffff"
command-text="#ffffff"
list-selected-background="#ff875f"
list-selected-text="#000000"
list-selected-inactive-background="#606060"
list-selected-inactive-text="#ffffff"
controls-text="#ffffff"
controls-highlight="#cc6600"
autocomplete-background="#606060"
autocomplete-text="#ffffff"
autocomplete-selected-background="#c2c2c2"
autocomplete-selected-text="#000000"
button-color-one="#ff4d4d"
button-color-two="#c2c2c2"
timeline-name-background="#9f0000"
timeline-name-text="#ffffff"
