#!/bin/sh

intern=LVDS-1
extern=HDMI-1

xrandr --output $intern --primary
if xrandr | grep "$extern connected"
then
    xrandr --output $extern --left-of $intern
    hsetroot -root -cover ~/.config/wallpaper/Reflections_of_the_night_sky.png
else
    hsetroot -cover ~/.config/wallpaper/Reflections_of_the_night_sky_16_9.png
fi

setxkbmap it
brightnessctl -q set 50%
xrdb ~/.Xresources
# xsetroot -cursor_name left_ptr

exec bspwm