#!/bin/sh
# dmenu_run improved
# if a command ends with "!", it is started in term.

termcmd="alacritty -e"

test -s $HOME/.dmenurc && . $HOME/.dmenurc

cmd="$(dmenu_path | dmenu -b -i -l 5 -fn "Hermit" -nb "#011627" -nf "#d6deeb" -sb "#0d486e" -sf "#ffffff" $@)"
case $cmd in
    *\! ) ${termcmd} "$(printf "%s" "${cmd}" | cut -d'!' -f1)";;
    * ) ${cmd} ;;
esac
exit